[features]
seeds = false
[programs.localnet]
fragmentor = "6jZDraLYUeT7Gau1Y4CEf8GPdbquacMEDJ6nZKYX6Q4m"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 js/tests/**/*.test.ts"
