[features]
seeds = false
[programs.localnet]
fragmentor = "CdYdVmD7bDbr2CfSHDhY5HP51ZV8weQsQBQgXiVzAyed"

[programs.devnet]
fragmentor = "CdYdVmD7bDbr2CfSHDhY5HP51ZV8weQsQBQgXiVzAyed"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 js/tests/**/*.test.ts"
