[features]
seeds = false
[programs.localnet]
fragmentor = "9SPvLNP6TAW4ZCtST8pmCCrKYt2gctRedmq1eWAu2Cwz"

[programs.devnet]
fragmentor = "FRAGFu59MRwy5KeEMnbzsUPa2JkwLVsaP7WbhF2r2Yh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "pnpm vitest"
